//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.06 at 03:33:20 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.jee-soft.cn/sqlgen", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hotent.tools.sqlgen.entity;
