//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.06 at 03:33:20 PM CST 
//


package com.hotent.tools.sqlgen.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resource complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resource">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="sql" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="template" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *       &lt;attribute name="table" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pk" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parentId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parentIdVal" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="variables" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mainTable" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fk" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resource", propOrder = {

})
public class Resource {

    @XmlElement(required = true)
    protected String sql;
    @XmlElement(required = true)
    protected String template;
    @XmlAttribute(name = "table", required = true)
    protected String table;
    @XmlAttribute(name = "pk", required = true)
    protected String pk;
    @XmlAttribute(name = "parentId")
    protected String parentId;
    @XmlAttribute(name = "parentIdVal")
    protected String parentIdVal;
    @XmlAttribute(name = "variables")
    protected String variables;
    @XmlAttribute(name = "mainTable")
    protected String mainTable;
    @XmlAttribute(name = "fk")
    protected String fk;

    /**
     * Gets the value of the sql property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSql() {
        return sql;
    }

    /**
     * Sets the value of the sql property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSql(String value) {
        this.sql = value;
    }

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplate() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplate(String value) {
        this.template = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTable(String value) {
        this.table = value;
    }

    /**
     * Gets the value of the pk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPk() {
        return pk;
    }

    /**
     * Sets the value of the pk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPk(String value) {
        this.pk = value;
    }

    /**
     * Gets the value of the parentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * Sets the value of the parentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentId(String value) {
        this.parentId = value;
    }

    /**
     * Gets the value of the parentIdVal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentIdVal() {
        return parentIdVal;
    }

    /**
     * Sets the value of the parentIdVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentIdVal(String value) {
        this.parentIdVal = value;
    }

    /**
     * Gets the value of the variables property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariables() {
        return variables;
    }

    /**
     * Sets the value of the variables property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariables(String value) {
        this.variables = value;
    }

    /**
     * Gets the value of the mainTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainTable() {
        return mainTable;
    }

    /**
     * Sets the value of the mainTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainTable(String value) {
        this.mainTable = value;
    }

    /**
     * Gets the value of the fk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFk() {
        return fk;
    }

    /**
     * Sets the value of the fk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFk(String value) {
        this.fk = value;
    }

}
